baseURL: "https://aakash.is-a.dev/"
title: Shinyzenith
paginate: 5
theme: PaperMod
disableHugoGeneratorInject: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Aakash Sharma
  description: "Programming isn't about what you know; it's about what you can figure out. - Chris Pine"
  keywords: [Blog, Portfolio, PaperMod]
  author: ["Aakash Sen Sharma"]
  images: ["https://avatars.githubusercontent.com/u/60808802?v=4"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://avatars.githubusercontent.com/u/60808802?v=4"
    favicon16x16: "https://avatars.githubusercontent.com/u/60808802?v=4"
    favicon32x32: "https://avatars.githubusercontent.com/u/60808802?v=4"
    apple_touch_icon: "https://avatars.githubusercontent.com/u/60808802?v=4"
    safari_pinned_tab: "https://avatars.githubusercontent.com/u/60808802?v=4"

  label:
    text: " "
    #icon: ""
    #iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: আকাশ
    subtitle: "Programming is not a science. Programming is a craft."
    imageUrl: "https://avatars.githubusercontent.com/u/60808802?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: About
        url: about
      - name: Blogs
        url: blogs

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: ""
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: github
      name: GitHub
      url: https://github.com/Shinyzenith
      weight: 10
    - identifier: email
      name: Email
      url: mailto:aakash@shinyzenith.xyz
      weight: 20
    - identifier: pgp
      name: PGP
      url: pgp
      weight: 30
    - identifier: tags
      name: Tags
      url: tags
      weight: 40
#outputs:
#home:
#- HTML
#- RSS
#- JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
